### ISSUE TITLE
[ 2021.11.04(Thur) 회의록]

### ISSUE THREAD

**Issue by hggew** [kotlin-with-prettiest/kotlin-with-prettiest#27]
# [ 2021.11.04(Thur) 회의록]

작성자 : 김현영

### 📋 회의 안건

1. 개인 프로젝트 진행 
    -  각자 주제 설정 완료 
2. 팀 프로젝트 주제
    -  후보 1 : 블랙보드 강의 알리미
    -  후보 2 : 식당 예약 어플
    -  후보 3 : 맛집 추천 및 기록 어플
    -  후보 4 : 세종대 졸업 여부 확인 + a 어플 

### 📋 다음주 할 내용

- 개인 프로젝트 완료 : 프로젝트 소개 및 제작 과정 설명
- 팀 프로젝트 주제 정하기

### 📈 진행 현황

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | 맛집 다이어리 |
|  @byhhh2 | 무비 다이어리 |
| @hggew | 환율 계산기 |
| @RightHennessy | 뮤직 다이어리 |

### ❓ 질문

- 이번주 질문은 없습니다.

### 🛠 개선 사항

- 개인 프로젝트 패널티
     -  미완성 시 30000원 납부
     - 기준 : 비밀투표로 결정

**Comment by RightHennessy** [comment]
확인했슴당 ~ !

**Comment by sally2596** [comment]
화긴~^^

**Comment by byhhh2** [comment]
확인 💨
