### ISSUE TITLE
[ 2021.11.11(Thur) 회의록]

### ISSUE THREAD

**Issue by hggew** [kotlin-with-prettiest/kotlin-with-prettiest#28]
# [ 2021.11.11(Thur) 회의록]

작성자 : 김현영

### 📋 회의 안건

1. 개인 프로젝트 발표
    
2. 팀 프로젝트 주제 선정
    - 블랙보드 강의 알리미
    - 다음주까지 [노션](https://six-eye-dd4.notion.site/887f6ac8b157452793cf6caf091f872d)에 세부기획 작성해오기

### 📋 다음주 할 내용

- 팀 프로젝트 기획

### 📈 진행 현황

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 |  <a href="https://github.com/kotlin-with-prettiest/PersonalProject_sally2596">맛집 다이어리</a> |
|  @byhhh2 | <a href="https://github.com/kotlin-with-prettiest/PersonalProject_movie">무비 다이어리</a> |
| @hggew | <a href="https://github.com/kotlin-with-prettiest/PersonalProject_hy">환율 계산기</a> |
| @RightHennessy | 뮤직 다이어리 |

### ❓ 질문

- 이번주 질문은 없습니다.

### 🛠 개선 사항

- 개인 프로젝트 미완성 패널티 삭제
- 다음주부터 슬랙 대신 디스코드 사용
- 2021.11.18 회의 9시 진행

**Comment by RightHennessy** [comment]
확인했습니다아 ~ 💛

**Comment by sally2596** [comment]
다들 노션에도 뭔가 끄적이고.. 디스코드도 들어와주세요..확인..

**Comment by byhhh2** [comment]
화긴 😉〰
